/**
 * ShaderCompiler.js
 *
 * WGSL helper utilities — preprocessor directives, GLSL→WGSL shim stubs
 * and platform-difference handling for the WebGL fallback path.
 *
 * Inspiration:
 *   - Babylon.js (Apache 2.0): WebGPUShaderProcessor
 *     https://github.com/BabylonJS/Babylon.js
 *
 * License: MIT — makr-code/GalaxyQuest
 */

'use strict';

/**
 * Very lightweight WGSL preprocessor — handles #define / #ifdef / #endif.
 *
 * @param {string} src      Raw WGSL source with optional preprocessor directives
 * @param {Object} defines  Key→value map (values are stringified into source)
 * @returns {string}
 */
function preprocessWGSL(src, defines = {}) {
  let out = src;

  // 1. Process #ifdef / #ifndef blocks FIRST (before value substitution so
  //    that keys like USE_BLOOM are still recognisable as identifiers)
  out = _processIfBlocks(out, defines);

  // 2. Strip any remaining #define lines (unsupported in WGSL)
  out = out.replace(/^#define\s+.*$/gm, '');

  // 3. Substitute constant values (e.g. WORKGROUP_SIZE → 64)
  for (const [key, val] of Object.entries(defines)) {
    out = out.replace(new RegExp(`\\b${key}\\b`, 'g'), String(val));
  }

  return out;
}

function _processIfBlocks(src, defines) {
  return src.replace(/#ifdef\s+(\w+)([\s\S]*?)#endif/g, (_, key, body) => {
    return key in defines ? body : '';
  }).replace(/#ifndef\s+(\w+)([\s\S]*?)#endif/g, (_, key, body) => {
    return !(key in defines) ? body : '';
  });
}

/**
 * Minimal GLSL ES 300 → WGSL attribute/uniform remapping stubs.
 * Not a full transpiler — used for simple post-effect shaders only.
 *
 * @param {string} glsl
 * @returns {string}
 */
function glslToWgslStub(glsl) {
  return glsl
    .replace(/\bgl_FragColor\b/g, 'fragColor')
    .replace(/\bgl_Position\b/g,  'output.position')
    .replace(/\btexture2D\b/g,    'textureSample')
    .replace(/\bvoid main\b/g,    '@fragment fn fs_main')
    .replace(/\bprecision\s+\w+\s+\w+;\s*/g, '');
}

/**
 * Inject standard GalaxyQuest engine header into a WGSL shader.
 * @param {string} src
 * @param {string} [label]
 * @returns {string}
 */
function injectHeader(src, label = 'gq-shader') {
  return `// GalaxyQuest Engine — ${label}\n// Auto-generated by ShaderCompiler.js\n\n${src}`;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { preprocessWGSL, glslToWgslStub, injectHeader };
} else {
  window.GQShaderCompiler = { preprocessWGSL, glslToWgslStub, injectHeader };
}
