'use strict';

(function () {
  function createGameContextRefs(opts = {}) {
    const {
      windowRef = (typeof window !== 'undefined' ? window : null),
      navigatorRef = (typeof navigator !== 'undefined' ? navigator : null),
      localStorageRef = (typeof localStorage !== 'undefined' ? localStorage : null),
      eventSourceCtor = (typeof EventSource !== 'undefined' ? EventSource : null),
      wm = null,
      api = null,
      audioTrackOptionsFallback = [],
      getApi = () => api,
      getAudioManager = () => null,
      getAutoTransitions = () => false,
      getColonies = () => [],
      getCurrentColony = () => null,
      getGalaxy3d = () => null,
      getGalaxy3dInitReason = () => '',
      getGalaxy3dQualityState = () => null,
      getGalaxyDb = () => null,
      getGalaxyModel = () => null,
      getGalaxyStars = () => [],
      getHotkeysBound = () => false,
      getPinnedStar = () => null,
      getRollStep = () => 0.05,
      getSettingsState = () => null,
      getUiState = () => null,
      getActiveRange = () => null,
      getActiveStar = () => null,
      getGalaxyAutoFramedOnce = () => false,
      getGalaxyHealthState = () => ({ last: null, lastCheckMs: 0, warned: false }),
      getGalaxyHydrationToken = () => 0,
      getSelectionState = () => null,
      getClusterSummary = () => [],
      getIsSystemMode = () => false,
      getZoomOrchestrator = () => null,
      setAudioTrackCatalogLoaded = () => {},
      setAudioTrackCatalogPromise = () => {},
      setAudioTrackOptions = () => {},
      setAutoTransitions = () => {},
      setGalaxy3dQualityState = () => {},
      setGalaxy3dInitReason = () => {},
      setGalaxy3d = () => {},
      setGalaxyAutoFramedOnce = () => {},
      setGalaxyHealthState = () => {},
      setGalaxyHydrationToken = () => {},
      setHotkeysBound = () => {},
      setGalaxySystemMax = () => {},
      setGalaxyStars = () => {},
      setPinnedStar = () => {},
      setZoomOrchestrator = () => {},
      clearGalaxyDb = () => null,
      clearGalaxyModel = () => {},
      clearGalaxyRendererStars = () => {},
      playMessageSend = () => {},
      updateFleetVectorsUiSafe = () => {},
      getSettingsController = () => null,
      getGalaxyController = () => null,
    } = opts;

    return {
      getApiRef: () => getApi(),
      getAudioManagerRef: () => getAudioManager(),
      getAutoTransitionsRef: () => !!getAutoTransitions(),
      getColoniesRef: () => getColonies(),
      getCurrentColonyRef: () => getCurrentColony(),
      getGalaxy3dRef: () => getGalaxy3d(),
      getGalaxy3dInitReasonRef: () => getGalaxy3dInitReason(),
      getGalaxy3dQualityStateRef: () => getGalaxy3dQualityState(),
      getGalaxyDbRef: () => getGalaxyDb(),
      getGalaxyModelRef: () => getGalaxyModel(),
      getGalaxyStarsRef: () => getGalaxyStars(),
      getHotkeysBoundRef: () => !!getHotkeysBound(),
      getLogApiRef: () => windowRef?.GQLog || null,
      getMetaRef: () => (windowRef?._GQ_meta || {}),
      getNavigatorRef: () => navigatorRef,
      getPinnedStarRef: () => getPinnedStar(),
      getRollStepRef: () => Number(getRollStep() || 0.05),
      getSettingsStateRef: () => getSettingsState(),
      getWmRef: () => wm,
      getUiStateRef: () => getUiState(),
      getLocalStorageRef: () => localStorageRef,
      getActiveRangeRef: () => getActiveRange(),
      getActiveStarRef: () => getActiveStar(),
      getGalaxyAutoFramedOnceRef: () => !!getGalaxyAutoFramedOnce(),
      getGalaxyHealthStateRef: () => getGalaxyHealthState(),
      getGalaxyHydrationTokenRef: () => getGalaxyHydrationToken(),
      getSelectionStateRef: () => getSelectionState(),
      getClusterSummaryRef: () => getClusterSummary(),
      getIsSystemModeRef: () => !!getIsSystemMode(),
      getZoomOrchestratorRef: () => getZoomOrchestrator(),
      setAudioTrackCatalogLoadedRef: (value) => setAudioTrackCatalogLoaded(value),
      setAudioTrackCatalogPromiseRef: (nextPromise) => setAudioTrackCatalogPromise(nextPromise),
      setAudioTrackOptionsRef: (nextOptions) => setAudioTrackOptions(Array.isArray(nextOptions) ? nextOptions : audioTrackOptionsFallback.slice()),
      setAutoTransitionsRef: (enabled) => setAutoTransitions(enabled),
      setGalaxy3dQualityStateRef: (value) => setGalaxy3dQualityState(value),
      setGalaxy3dInitReasonRef: (reason) => setGalaxy3dInitReason(reason),
      setGalaxy3dRef: (renderer) => setGalaxy3d(renderer),
      setGalaxyAutoFramedOnceRef: (value) => setGalaxyAutoFramedOnce(value),
      setGalaxyHealthStateRef: (nextState) => setGalaxyHealthState(nextState),
      setGalaxyHydrationTokenRef: (value) => setGalaxyHydrationToken(value),
      setHotkeysBoundRef: (value) => setHotkeysBound(value),
      setGalaxySystemMaxRef: (value) => setGalaxySystemMax(value),
      setGalaxyStarsRef: (stars) => setGalaxyStars(stars),
      setPinnedStarRef: (star) => setPinnedStar(star),
      setZoomOrchestratorRef: (next) => setZoomOrchestrator(next),
      clearGalaxyDbRef: () => clearGalaxyDb(),
      clearGalaxyModelRef: () => clearGalaxyModel(),
      clearGalaxyRendererStarsRef: () => clearGalaxyRendererStars(),
      playMessageSendRef: () => playMessageSend(),
      updateFleetVectorsUiSafeRef: (root) => updateFleetVectorsUiSafe(root),
      eventSourceFactoryRef: (url) => new eventSourceCtor(url),
      getFtlMapRef: () => windowRef?._GQ_ftl_map || null,
      getGalaxyFleetsRef: () => windowRef?._GQ_fleets || [],
      getGalaxyRendererBootstrapApiRef: () => windowRef?.GQGalaxyRendererBootstrap || null,
      getLevelRendererOptionsRef: () => windowRef?.__GQ_LEVEL_RENDERER_OPTIONS || {},
      wmBody: wm?.body?.bind(wm),
      wmIsOpen: wm?.isOpen?.bind(wm),
      wmOpen: wm?.open?.bind(wm),
      wmRefresh: wm?.refresh?.bind(wm),
      apiDeleteMsg: api?.deleteMsg?.bind(api),
      apiFactions: api?.factions?.bind(api),
      apiGalaxy: api?.galaxy?.bind(api),
      apiHealth: api?.health?.bind(api),
      apiNetworkHealth: api?.networkHealth?.bind(api),
      apiReadMsg: api?.readMsg?.bind(api),
      apiSendMsg: api?.sendMsg?.bind(api),
      applyRuntimeSettingsRef: () => getSettingsController().applyRuntimeSettings(),
      refreshAudioUiRef: () => getSettingsController().refreshAudioUi(),
      refreshThemeSettingsUiRef: () => getSettingsController().refreshThemeSettingsUi(),
      saveUiSettingsRef: () => getSettingsController().saveUiSettings(),
      galaxyApplyMagnetPresetRef: (presetName, root) => getGalaxyController().applyMagnetPreset(presetName, root),
      galaxyLoadStars3DRef: (root) => getGalaxyController().loadStars3D(root),
      galaxyTriggerNavActionRef: (action, rootRef) => getGalaxyController().triggerNavAction(action, rootRef),
      galaxyUpdateClusterHeatmapUiRef: (root) => getGalaxyController().updateClusterHeatmapUi(root),
      galaxyUpdateCoreFxUiRef: (root) => getGalaxyController().updateCoreFxUi(root),
      galaxyUpdateFleetVectorsUiRef: (root) => getGalaxyController().updateFleetVectorsUi(root),
      galaxyUpdateLegacyFallbackUiRef: (root) => getGalaxyController().updateLegacyFallbackUi(root),
      galaxyUpdateMagnetUiRef: (root) => getGalaxyController().updateMagnetUi(root),
      apiGalaxyBootstrapRef: (galaxyIndex, fromSystem, toSystem, maxPoints) =>
        (typeof api?.galaxyBootstrap === 'function' ? api.galaxyBootstrap(galaxyIndex, fromSystem, toSystem, maxPoints) : null),
      apiGalaxyMetaRef: (galaxyIndex) => (typeof api?.galaxyMeta === 'function' ? api.galaxyMeta(galaxyIndex) : null),
      apiGalaxyStarsRef: (galaxyIndex, fromSystem, toSystem, requestMaxPoints, requestOpts) =>
        api.galaxyStars(galaxyIndex, fromSystem, toSystem, requestMaxPoints, requestOpts),
    };
  }

  const api = { createGameContextRefs };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = api;
  } else {
    window.GQRuntimeGameContextRefs = api;
  }
})();
